equinix/pulumi-equinix

docs/resource/equinix_metal_bgp_session.examples.md

fix: add newlines before closing shortcode in BGP session examples

---

go.work.sum
provider/cmd/pulumi-resource-equinix/schema.json
provider/go.mod
provider/go.sum
sdk/dotnet/Fabric/CloudRouter.cs
sdk/go/equinix/fabric/cloudRouter.go
sdk/go/equinix/fabric/pulumiTypes.go
sdk/java/src/main/java/com/equinix/pulumi/fabric/CloudRouter.java
sdk/java/src/main/java/com/equinix/pulumi/fabric/CloudRouterArgs.java
sdk/java/src/main/java/com/equinix/pulumi/fabric/inputs/CloudRouterState.java
sdk/nodejs/fabric/cloudRouter.ts
sdk/python/pulumi_equinix/fabric/cloud_router.py

The upstream submodule was initially added using the last commit, but the upgrade-provider pulumi tool needs the SHA of a tag. I have manually checkout upstream to [v1.19.0](https://github.com/equinix/terraform-provider-equinix/releases/tag/v1.19.0) and updated the go dependencies to that version as well
closed https://github.com/equinix/pulumi-equinix/pull/31 in favor of this PR

Fix upstream to tag

---

.github/workflows/release.yml

Prev release workflow was failing in https://github.com/equinix/pulumi-equinix/actions/runs/6789447917/job/18456647854

fix: add missing variable in release gh action

---

patches/0001-pulumi-user-agent.patch
patches/0002-shim-to-expose-internal-provider.patch
patches/0003-remove-provider-meta.patch

Provider was constantly failing in sdk v2 resources with the error in screenshot below. It fails in https://github.com/pulumi/pulumi-terraform-bridge/blob/f6013b69e741bc73632fd42ba2b4630a1f2cc3ff/pkg/tfshim/sdk-v2/provider2.go#L290 and seems to me an error in the terraform bridge plugin. I can't find any explanation why it takes the value of Config instead of Meta. 'm going to open an issue in the bridge plugin but for now I have added this patch to remove the ProviderMetaSchema from the upstream terraform provider, which in fact has no use here in pulumi.

fix: patch to remove failing provider meta schema

---

renovate.json

SDKs are autogenerated and should be ignored by renovate

chore: renovate should ignore sdk dependencies

---

docs/resource/equinix_fabric_cloud_router.examples.md

Added project_id block to Fabric Cloud Router Example because project_id is required parameter.
Refrence: https://app.swaggerhub.com/apis/equinix-api/fabric/4.13#/Cloud%20Routers/createCloudRouter

fix: Adding project_id block to fabric-cloud-router examples

---

.github/workflows/release.yml
.goreleaser.yml

Necessary changes to the goreleaser configuration file were not included in the previous PR #99 making it fail in https://github.com/equinix/pulumi-equinix/actions/runs/9659514911/job/26643074014
- version must be specified: `version: 2`
- `changelog.skip` replaced with `changelog.disable`
- Since version must be specified I have locked the version in the gh action to `~> v2`

update goreleaser config file and lock to version 2

---

.github/actions/upgrade-provider/action.yml
.github/workflows/upgrade-bridge.yml
.github/workflows/upgrade-provider.yml

upgrade-provider tool tries to assign the PR to the user who created it. Since we don't have an Equinix bot user, we are using the GITHUB_TOKEN. This results in an error when trying to assign the PR to the user of the token (github-action). As a workaround we override the assign user. The pulumi-upgrade-provider-action does not have this option so we temporarily overwrite the action locally with a pr-assign input that takes `github.actor` by default.
ERROR: GraphQL: Could not resolve to a User with the login of 'github-actions[bot]'. (u000)
https://github.com/equinix/pulumi-equinix/actions/runs/9976483769/job/27568775953

chore(ci): override upgrade-provider action

---

.github/workflows/upgrade-bridge.yml
.github/workflows/upgrade-provider.yml

This adds the `pr-title-prefix` argument to the upgrade steps in the upgrade-bridge and upgrade-provider workflows.  In the case where we were using the official Pulumi upgrade action, this upgrades that action to the latest version, v0.0.12.  That version introduced the `pr-title-prefix` argument and matches the base code of our custom action.
Part of #114

chore(ci): add feature prefix to automated upgrade PRs

---

.github/workflows/release.yml
.goreleaser.yml
.releaserc.json

This converts the release workflow to a push-button workflow.  Instead of pushing a new tag to create a new Pulumi provider release, this updated workflow determines the next version number by analyzing the Conventional Commits tags on all commits made to `main` since the last release.  The GitHub release notes are generated from the commit log.  The GoReleaser config is updated so that GoReleaser will attach binaries to the GitHub release that was created by semantic-release-action instead of expecting to create the release itself.

chore(ci): create release with semantic-release-action

---

.github/workflows/check-upstream-upgrade.yml

workflow `check-upstream-upgrade` is consistently failing with error:
```
fatal: remote error: upload-pack: not our ref 0028d0d7d396775e3c57b122bf1ca8f9e5b020e3
Errors during submodule fetch:
upstream
```
I'm not sure what the problem is but seems to be a conflict between the steps in the command `upgrade-provider` and the version that action/checkout gets. The `upgrade-provider` command runs `git submodule update --force --init` so we can continue using action/checkout without submodules

chore(ci): remove submodules init from actions/checkout

---

.github/workflows/upgrade-provider.yml

It turns out that scheduled GitHub Actions workflows do not run with the `github-actions[bot]` actor.  Instead the actor in those jobs appears to be whoever last did a `git push` affecting the scheduled workflow file:
https://github.com/orgs/community/discussions/25067#discussioncomment-7178233
This updates the upgrade-provider workflow so that, if the workflow was triggered by a `schedule` event, the workflow will use the default assignee.

chore(ci): use default PR assignee for scheduled workflows

---

Makefile
scripts/generate_examples.sh

chore: install pulumictl in makefile

---

.github/workflows/check-upstream-upgrade.yml
.github/workflows/upgrade-bridge.yml
.github/workflows/upgrade-provider.yml

GitHub events generated by the built-in, automatic GitHub Actions token are explicitly ignored by GitHub Actions.  This means that if an issue or pull request is created with the built-in token, that issue or pull request will not trigger other GitHub Actions workflows.
We previously worked around this issue by switching to scheduled workflows where necessary, but this leads to a large number of duplicate pull requests.  Using a custom bot token for the `upgrade-provider` command allows us to roll back the move to scheduled jobs and rely on GitHub events to trigger the necessary workflows on-demand.

chore(ci): switch to bot token for some GitHub Actions workflows

---

examples/metal/ssh_key/csharp/equinix-metal-ssh_key.csproj
examples/network/file/csharp/equinix-network-file.csproj
scripts/generate_examples.sh

The go examples require a specific version in go.mod. 
~This simply makes up the new version, although sometimes the new version will just be a fix and the version specified in the go examples will be higher than the latest available tag~
This adds label `latest` in go.mod pulumi-equinix/sdk import
```
require (
github.com/equinix/pulumi-equinix/sdk latest
github.com/pulumi/pulumi/sdk/v3 v3.128.0
)
```

chore: use `latest` version of the provider for go.mod in examples

---

.github/workflows/release.yml

https://github.com/equinix/pulumi-equinix/actions/runs/10603255187/job/29387507884 failed because pulumi/publish-go-sdk-action adds the "v" to the version. This can be fixed by taking the `new_release_version` output of cycjimmy/semantic-release-action instead of  `new_release_git_tag`

fix: using wrong semantic-release-action output

---

.github/workflows/release.yml
.github/workflows/run-acceptance-tests.yml

- v3 will also be deprecated this year. There are no [breaking changes ](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) that impact current usage
- actions/download-artifact upgraded accordingly https://github.com/actions/download-artifact?tab=readme-ov-file#breaking-changes

chore: upgrade deprecated action upload-artifact

---

renovate.json

~The `sdk` folder is completely auto-generated so we don't want `renovate` updating anything there.~
I came across this while checking #196 #197 which I don't understand because "sdk/**" was already specified

chore: renovate to ignorepaths with dotnet files

---

renovate.json

I misinterpreted the function `ignorePresets` in #202, which actually ignores the default behavior of ignoring [ignoreModulesAndTests](https://docs.renovatebot.com/presets-default/#ignoremodulesandtests). Merging this change should autoclose #203 where renovate is trying to update content in `**/examples/**`

chore: undo ignore renovate default behavior

---

.github/workflows/run-acceptance-tests.yml

We recently configured the provider upgrade workflow to skip mapping errors so that hand-written PRs can be smaller & focused on adding/removing resource mappings.  Based on recent provider upgrade PRs it appears that we also need to skip mapping errors in the acceptance tests workflow so that the automated upgrade PRs can pass CI.

chore(ci): skip mapping errors for acceptance tests

---

Makefile

The example generator script includes some code to replace the current Equinix Pulumi plugin version in generated examples with `< 1.0.0` (or the equivalent per language).  The script uses `.pulumi/bin/pulumictl get version --language generic` to determine the version number that should be replaced.  However, the examples are not necessarily generated to reference that plugin version.  The version referenced in examples appears to come from `provider/cmd/pulumi-resource-equinix/schema-embed.json`.
This adds `build_schema` as a dependency of the `only_provider` Make task.  The `only_provider` task is already a dependency of the `examples` task and the files produced by `build_schema` are necessary for `only_provider`.
This change ensures that the schema files are up-to-date before examples …

chore: ensure schema-embed.json is accurate when examples are generated

---

.github/workflows/upgrade-bridge.yml
.github/workflows/upgrade-provider.yml

We briefly switched to a fork of the Pulumi upgrade action in order to use a consistent Go version in all places in our GitHub actions.  The change from our fork has been adopted upstream so we can go back to using the latest release of the official action.

chore(ci): switch back to official Pulumi upgrade action

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

This updates the devcontainer definition so that the dev container can be used instead of installing all of the necessary tools directly on a development machine.

chore: update devcontainer

---

Makefile
upstream.sh

This removes the copy of `upstream.sh` in the repo root as well as some dangling references to the `upstream_old.sh` script that was removed in an earlier PR.

chore: clean up unused files

---

Makefile

A couple months ago, `pulumi/upgrade-provider` was changed to expect the existence of a `generate_sdks` task instead of a `build_sdks` task.  As a result of this change, our provider upgrade workflow is failing.
This follows [the suggestion in a comment on the `upgrade-provider` change PR](https://github.com/pulumi/upgrade-provider/pull/312#issuecomment-2851135278) to alias the `build_sdks` task as `generate_sdks`, which should fix the upgrade workflow.

chore(ci): alias build_sdks as generate_sdks to fix upgrades
